version: 2.1

orbs:
    python: circleci/python@1.5.0

jobs:
    build-and-test: 
        - image: cimg/python:3.10.2

    steps:
        - checkout
        - restore_cache:
            keys:
                - v1-dependencies-{{ checksum "requirements.txt" }}
                - v1-dependencies-
        - run:
            name: Install python dependencies
            command: |
                python3 -m venv venv 
                . venv/bin/activate
                make install
            
        - save_cache:
            paths:
                - ./venv
            key: v1-dependencies-{{ checksum "requirements.txt" }}
        - run:
            name: run lint
            command: |
                . venv/bin/activate
                make lint 

workflows:
    sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
        jobs:
            - build-and-test